image: node:18.16.0

default:
  tags:
    - power

stages:
  - build
  - test
  - deploy


build-job:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - node -v
    - yarn
    - yarn build
  artifacts:
    paths:
      - build

test-job:
  stage: test
  cache:
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn test

pages:
  stage: deploy
  dependencies: 
    - build
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main